---
name: inspec-exec

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
      - name: Install Inspec upstream packages
        run: |
          curl -O https://packages.chef.io/files/stable/inspec/5.12.2/ubuntu/20.04/inspec_5.12.2-1_amd64.deb
          sudo apt-get install -y ./inspec_5.12.2-1_amd64.deb
          sudo mkdir -p /etc/chef/accepted_licenses
          sudo touch /etc/chef/accepted_licenses/inspec
      - name: Environment
        run: |
          set -x
          env
          which inspec || true
      - name: Run Inspec exec
        run: inspec exec .
        continue-on-error: true
      # https://docs.umbrella.com/deployment-umbrella/docs/point-your-dns-to-cisco
      - name: Configure Umbrella
        run: |
          set -x
          cat /etc/resolv.conf
          { echo "nameserver 208.67.222.222"; echo "nameserver 208.67.220.220"; } | sudo tee /etc/resolv.conf
          cat /etc/resolv.conf
      - name: Troubleshooting
        run: |
          set -x
          nslookup -type=text debug.opendns.com.
          dig debug.opendns.com txt
          host www.google.com
          curl -v https://welcome.umbrella.com/
          curl -vk https://examplemalwaredomain.com
        continue-on-error: true
      - name: Run Inspec exec
        run: inspec exec .
